
Vagrant.configure("2") do |config|
  # The docker host VM
  config.vm.box = "xk_test/boot2docker-example"

  #sync local files to the docker host VM
  config.vm.synced_folder "../", "/vagrant"

  #virtualbox config
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "3072"]
  end
end
